export {
  isOrbisTransportError,
  OrbisTransportError,
  type OrbisTransportErrorCode,
  type OrbisTransportErrorOptions,
} from "./errors";
export {
  acceptSecureInitiatorHandshake,
  constantTimeEqualBase64Url,
  copySecretBytes,
  createPairingSecret,
  createSecureInitiatorHandshake,
  fingerprintPublicKey,
  generateDeviceIdentity,
  ORBIS_E2EE_PROTOCOL_VERSION,
  ORBIS_E2EE_SUITE,
  OrbisSecureChannel,
  pairingSafetyNumber,
  pairingSecretVerifier,
  secureHelloEnvelopeSchema,
  secureMessageEnvelopeSchema,
  secureWelcomeEnvelopeSchema,
  serializedDeviceIdentitySchema,
  type InitiatorSecurity,
  type OrbisE2eeHandshakeMode,
  type PairingHandshakeCredentials,
  type SecureHelloEnvelope,
  type SecureInitiatorHandshake,
  type SecureInitiatorOptions,
  type SecureMessageEnvelope,
  type SecureRandom,
  type SecureResponderHandshake,
  type SecureResponderOptions,
  type SecureResponderPeer,
  type SecureWelcomeEnvelope,
  type SerializedDeviceIdentity,
} from "./e2ee";
export {
  activeHostEndpoints,
  hostEndpointKindSchema,
  hostEndpointKinds,
  hostEndpointManifestSchema,
  hostEndpointSchema,
  normalizeHostEndpointManifest,
  type HostEndpoint,
  type HostEndpointManifest,
} from "./endpoints";
export {
  OrbisTransportClient,
  type AccessTokenProvider,
  type AccessTokenRequest,
  type FetchImplementation,
  type OrbisTransportClientOptions,
  type TransportOperationOptions,
  type WaitForPairingOptions,
} from "./http-client";
export {
  OrbisRemoteHostConnection,
  type AcceptRemoteHostOptions,
  type ConnectRemoteHostOptions,
  type ConnectRemoteHostUplinkOptions,
  type RemoteHostAcknowledgement,
  type RemoteHostConnectionState,
  type RemoteHostPeer,
  type RemoteHostPeerError,
  type RemoteHostResolvedPeer,
  type RemoteHostRequestContext,
  type RemoteHostRequestHandler,
} from "./host-websocket";
export {
  OrbisRemoteHarnessRouter,
  type RemoteHarnessConnector,
  type RemoteHarnessDefinition,
  type RemoteHarnessEventBroadcaster,
  type RemoteHarnessSession,
} from "./harness-connector";
export {
  createRemoteDiagnosticsEnvelope,
  fingerprintRemoteDiagnosticsValue,
  ORBIS_REMOTE_DIAGNOSTICS_FORMAT,
  ORBIS_REMOTE_DIAGNOSTICS_FORMAT_VERSION,
  ORBIS_REMOTE_DIAGNOSTICS_REDACTION_PROFILE,
  redactStoredRemoteServer,
  remoteDiagnosticsFileName,
  remoteDiagnosticsFingerprint,
  sanitizeRemoteDiagnosticsText,
  serializeRemoteDiagnostics,
  type OrbisRemoteDiagnosticsCorrelation,
  type OrbisRemoteDiagnosticsEnvelope,
  type OrbisRemoteDiagnosticsEnvelopeInput,
  type OrbisRemoteDiagnosticsLatestFailure,
  type OrbisRemoteDiagnosticsRedactionManifest,
  type OrbisRemoteDiagnosticsRetentionManifest,
  type OrbisRemoteDiagnosticsSource,
  type OrbisRemoteDiagnosticsWindow,
  type RedactedRemoteDiagnosticsEndpoint,
  type RedactedRemoteDiagnosticsHarness,
  type RedactedRemoteDiagnosticsServer,
  type RemoteDiagnosticsStoredEndpoint,
  type RemoteDiagnosticsStoredHarness,
  type RemoteDiagnosticsStoredServer,
} from "./diagnostics";
export {
  ORBIS_PAIRING_URI_SCHEME,
  parsePairingInvitation,
  serializePairingInvitation,
  type PairingBootstrapEndpoint,
  type PairingInvitation,
} from "./pairing-invitation";
export {
  connectionTicketRequestSchema,
  connectionTicketSchema,
  incomingHostTransportFrameSchema,
  incomingTransportFrameSchema,
  jsonValueSchema,
  ORBIS_REMOTE_SCOPE_VALUES,
  ORBIS_REMOTE_SCOPES,
  ORBIS_RELAY_UPLINK_SUBPROTOCOL,
  ORBIS_TRANSPORT_PROTOCOL_VERSION,
  ORBIS_TRANSPORT_SUBPROTOCOL,
  pairingApprovalInputSchema,
  pairingChallengeSchema,
  pairingInitiationInputSchema,
  pairingLookupSchema,
  pairingStatusSchema,
  peerDescriptorSchema,
  relayPeerCloseFrameSchema,
  remoteCredentialSchema,
  remoteHarnessSchema,
  remoteHostSchema,
  remoteScopeModeSchema,
  remoteScopePolicyAllows,
  resolveRemoteScopes,
  serverAcknowledgementSchema,
  serverErrorResponseSchema,
  transportAckFrameSchema,
  transportActivateFrameSchema,
  transportActivatedFrameSchema,
  transportCancelFrameSchema,
  transportCapabilitiesSchema,
  transportErrorFrameSchema,
  transportEventFrameSchema,
  transportEventSchema,
  transportEndpointManifestFrameSchema,
  transportHelloFrameSchema,
  transportRequestFrameSchema,
  transportResponseFrameSchema,
  transportWelcomeFrameSchema,
  type ApprovedPairingStatus,
  type ConnectionTicket,
  type ConnectionTicketRequest,
  type IncomingTransportFrame,
  type IncomingHostTransportFrame,
  type JsonValue,
  type PairingApprovalInput,
  type PairingChallenge,
  type PairingInitiationInput,
  type PairingLookup,
  type PairingStatus,
  type PeerDescriptor,
  type RemoteCredential,
  type RemoteHost,
  type RemoteScopeMode,
  type TransportAckFrame,
  type TransportActivateFrame,
  type TransportActivatedFrame,
  type TransportCancelFrame,
  type TransportCapabilities,
  type TransportEvent,
  type TransportEndpointManifestFrame,
  type RelayPeerCloseFrame,
  type TransportHelloFrame,
  type TransportRequestFrame,
  type TransportWelcomeFrame,
} from "./protocol";
export {
  OrbisRemoteConnection,
  type ConnectEndpointOptions,
  type ConnectRemoteOptions,
  type RemoteConnectionApplicationFrame,
  type RemoteConnectionApplicationFrameListener,
  type RemoteConnectionClose,
  type RemoteConnectionCloseListener,
  type RemoteConnectionDiagnostic,
  type RemoteConnectionDiagnosticListener,
  type RemoteConnectionState,
  type HostEndpointManifestListener,
  type RemoteRequestOptions,
  type TransportEventListener,
  type WebSocketEvent,
  type WebSocketEventListener,
  type WebSocketEventType,
  type WebSocketFactory,
  type WebSocketFactoryRequest,
  type WebSocketLike,
} from "./websocket";
